# python3 analytical_compare.py -c configFiles/config_size1024_alltoall_disGE_packetFixed_dr0p07.json &
# python3 analytical_compare.py -c configFiles/config_size1024_alltoall_disGE_packetUniform_dr0p07.json &
# python3 analytical_compare.py -c configFiles/config_size1024_alltoall_disPoisson_packetFixed_dr0p07.json &
# python3 analytical_compare.py -c configFiles/config_size1024_alltoall_disPoisson_packetUniform_dr0p07.json &
# python3 analytical_compare.py -c configFiles/config_size1024_broadcast_disGE_packetFixed_dr0p02.json &
# python3 analytical_compare.py -c configFiles/config_size1024_broadcast_disGE_packetFixed_dr0p05.json &
# python3 analytical_compare.py -c configFiles/config_size1024_broadcast_disGE_packetFixed_dr0p07.json &
# python3 analytical_compare.py -c configFiles/config_size1024_broadcast_disGE_packetUniform_dr0p02.json &
# python3 analytical_compare.py -c configFiles/config_size1024_broadcast_disGE_packetUniform_dr0p05.json &
# python3 analytical_compare.py -c configFiles/config_size1024_broadcast_disGE_packetUniform_dr0p07.json &
# python3 analytical_compare.py -c configFiles/config_size1024_broadcast_disPoisson_packetFixed_dr0p02.json &
# python3 analytical_compare.py -c configFiles/config_size1024_broadcast_disPoisson_packetFixed_dr0p05.json &
# python3 analytical_compare.py -c configFiles/config_size1024_broadcast_disPoisson_packetFixed_dr0p07.json &
# python3 analytical_compare.py -c configFiles/config_size1024_broadcast_disPoisson_packetUniform_dr0p02.json &
# python3 analytical_compare.py -c configFiles/config_size1024_broadcast_disPoisson_packetUniform_dr0p05.json &
# python3 analytical_compare.py -c configFiles/config_size1024_broadcast_disPoisson_packetUniform_dr0p07.json &
# python3 analytical_compare.py -c configFiles/config_size1024_incast_disGE_packetFixed_dr0p02.json &
# python3 analytical_compare.py -c configFiles/config_size1024_incast_disGE_packetFixed_dr0p05.json &
# python3 analytical_compare.py -c configFiles/config_size1024_incast_disGE_packetFixed_dr0p07.json &
# python3 analytical_compare.py -c configFiles/config_size1024_incast_disGE_packetUniform_dr0p02.json &
# python3 analytical_compare.py -c configFiles/config_size1024_incast_disGE_packetUniform_dr0p05.json &
# python3 analytical_compare.py -c configFiles/config_size1024_incast_disGE_packetUniform_dr0p07.json &
# python3 analytical_compare.py -c configFiles/config_size1024_incast_disPoisson_packetFixed_dr0p02.json &
# python3 analytical_compare.py -c configFiles/config_size1024_incast_disPoisson_packetFixed_dr0p05.json &
# python3 analytical_compare.py -c configFiles/config_size1024_incast_disPoisson_packetFixed_dr0p07.json &
# python3 analytical_compare.py -c configFiles/config_size1024_incast_disPoisson_packetUniform_dr0p02.json &
# python3 analytical_compare.py -c configFiles/config_size1024_incast_disPoisson_packetUniform_dr0p05.json &
# python3 analytical_compare.py -c configFiles/config_size1024_incast_disPoisson_packetUniform_dr0p07.json &
# python3 analytical_compare.py -c configFiles/config_size128_alltoall_disGE_packetFixed_dr0p2.json &
# python3 analytical_compare.py -c configFiles/config_size128_alltoall_disGE_packetFixed_dr0p39.json &
# python3 analytical_compare.py -c configFiles/config_size128_alltoall_disGE_packetFixed_dr0p59.json &
# python3 analytical_compare.py -c configFiles/config_size128_alltoall_disGE_packetUniform_dr0p2.json &
# python3 analytical_compare.py -c configFiles/config_size128_alltoall_disGE_packetUniform_dr0p39.json &
# python3 analytical_compare.py -c configFiles/config_size128_alltoall_disGE_packetUniform_dr0p59.json &
# python3 analytical_compare.py -c configFiles/config_size128_alltoall_disPoisson_packetFixed_dr0p2.json &
# python3 analytical_compare.py -c configFiles/config_size128_alltoall_disPoisson_packetFixed_dr0p39.json &
# python3 analytical_compare.py -c configFiles/config_size128_alltoall_disPoisson_packetFixed_dr0p59.json &
# python3 analytical_compare.py -c configFiles/config_size128_alltoall_disPoisson_packetUniform_dr0p2.json &
# python3 analytical_compare.py -c configFiles/config_size128_alltoall_disPoisson_packetUniform_dr0p39.json &
# python3 analytical_compare.py -c configFiles/config_size128_alltoall_disPoisson_packetUniform_dr0p59.json &
# python3 analytical_compare.py -c configFiles/config_size128_broadcast_disGE_packetFixed_dr0p2.json &
# python3 analytical_compare.py -c configFiles/config_size128_broadcast_disGE_packetFixed_dr0p39.json &
# python3 analytical_compare.py -c configFiles/config_size128_broadcast_disGE_packetFixed_dr0p59.json &
# python3 analytical_compare.py -c configFiles/config_size128_broadcast_disGE_packetUniform_dr0p2.json &
# python3 analytical_compare.py -c configFiles/config_size128_broadcast_disGE_packetUniform_dr0p39.json &
# python3 analytical_compare.py -c configFiles/config_size128_broadcast_disGE_packetUniform_dr0p59.json &
# python3 analytical_compare.py -c configFiles/config_size128_broadcast_disPoisson_packetFixed_dr0p2.json &
# python3 analytical_compare.py -c configFiles/config_size128_broadcast_disPoisson_packetFixed_dr0p39.json &
# python3 analytical_compare.py -c configFiles/config_size128_broadcast_disPoisson_packetFixed_dr0p59.json &
# python3 analytical_compare.py -c configFiles/config_size128_broadcast_disPoisson_packetUniform_dr0p2.json &
# python3 analytical_compare.py -c configFiles/config_size128_broadcast_disPoisson_packetUniform_dr0p39.json &
# python3 analytical_compare.py -c configFiles/config_size128_broadcast_disPoisson_packetUniform_dr0p59.json &
# python3 analytical_compare.py -c configFiles/config_size128_incast_disGE_packetFixed_dr0p2.json &
# python3 analytical_compare.py -c configFiles/config_size128_incast_disGE_packetFixed_dr0p39.json &
# python3 analytical_compare.py -c configFiles/config_size128_incast_disGE_packetFixed_dr0p59.json &
# python3 analytical_compare.py -c configFiles/config_size128_incast_disGE_packetUniform_dr0p2.json &
# python3 analytical_compare.py -c configFiles/config_size128_incast_disGE_packetUniform_dr0p39.json &
# python3 analytical_compare.py -c configFiles/config_size128_incast_disGE_packetUniform_dr0p59.json &
# python3 analytical_compare.py -c configFiles/config_size128_incast_disPoisson_packetFixed_dr0p2.json &
# python3 analytical_compare.py -c configFiles/config_size128_incast_disPoisson_packetFixed_dr0p39.json &
# python3 analytical_compare.py -c configFiles/config_size128_incast_disPoisson_packetFixed_dr0p59.json &
# python3 analytical_compare.py -c configFiles/config_size128_incast_disPoisson_packetUniform_dr0p2.json &
# python3 analytical_compare.py -c configFiles/config_size128_incast_disPoisson_packetUniform_dr0p39.json &
# python3 analytical_compare.py -c configFiles/config_size128_incast_disPoisson_packetUniform_dr0p59.json &
# python3 analytical_compare.py -c configFiles/config_size16_alltoall_disGE_packetFixed_dr1p67.json &
# python3 analytical_compare.py -c configFiles/config_size16_alltoall_disGE_packetFixed_dr3p33.json &
# python3 analytical_compare.py -c configFiles/config_size16_alltoall_disGE_packetFixed_dr5p0.json &
# python3 analytical_compare.py -c configFiles/config_size16_alltoall_disGE_packetUniform_dr1p67.json &
# python3 analytical_compare.py -c configFiles/config_size16_alltoall_disGE_packetUniform_dr3p33.json &
# python3 analytical_compare.py -c configFiles/config_size16_alltoall_disGE_packetUniform_dr5p0.json &
# python3 analytical_compare.py -c configFiles/config_size16_alltoall_disPoisson_packetFixed_dr1p67.json &
# python3 analytical_compare.py -c configFiles/config_size16_alltoall_disPoisson_packetFixed_dr3p33.json &
# python3 analytical_compare.py -c configFiles/config_size16_alltoall_disPoisson_packetFixed_dr5p0.json &
# python3 analytical_compare.py -c configFiles/config_size16_alltoall_disPoisson_packetUniform_dr1p67.json &
# python3 analytical_compare.py -c configFiles/config_size16_alltoall_disPoisson_packetUniform_dr3p33.json &
# python3 analytical_compare.py -c configFiles/config_size16_alltoall_disPoisson_packetUniform_dr5p0.json &
# python3 analytical_compare.py -c configFiles/config_size16_broadcast_disGE_packetFixed_dr1p67.json &
# python3 analytical_compare.py -c configFiles/config_size16_broadcast_disGE_packetFixed_dr3p33.json &
# python3 analytical_compare.py -c configFiles/config_size16_broadcast_disGE_packetFixed_dr5p0.json &
# python3 analytical_compare.py -c configFiles/config_size16_broadcast_disGE_packetUniform_dr1p67.json &
# python3 analytical_compare.py -c configFiles/config_size16_broadcast_disGE_packetUniform_dr3p33.json &
# python3 analytical_compare.py -c configFiles/config_size16_broadcast_disGE_packetUniform_dr5p0.json &
# python3 analytical_compare.py -c configFiles/config_size16_broadcast_disPoisson_packetFixed_dr1p67.json &
# python3 analytical_compare.py -c configFiles/config_size16_broadcast_disPoisson_packetFixed_dr3p33.json &
# python3 analytical_compare.py -c configFiles/config_size16_broadcast_disPoisson_packetFixed_dr5p0.json &
# python3 analytical_compare.py -c configFiles/config_size16_broadcast_disPoisson_packetUniform_dr1p67.json &
# python3 analytical_compare.py -c configFiles/config_size16_broadcast_disPoisson_packetUniform_dr3p33.json &
# python3 analytical_compare.py -c configFiles/config_size16_broadcast_disPoisson_packetUniform_dr5p0.json &
# python3 analytical_compare.py -c configFiles/config_size16_incast_disGE_packetFixed_dr1p67.json &
# python3 analytical_compare.py -c configFiles/config_size16_incast_disGE_packetFixed_dr3p33.json &
# python3 analytical_compare.py -c configFiles/config_size16_incast_disGE_packetFixed_dr5p0.json &
# python3 analytical_compare.py -c configFiles/config_size16_incast_disGE_packetUniform_dr1p67.json &
# python3 analytical_compare.py -c configFiles/config_size16_incast_disGE_packetUniform_dr3p33.json &
# python3 analytical_compare.py -c configFiles/config_size16_incast_disGE_packetUniform_dr5p0.json &
# python3 analytical_compare.py -c configFiles/config_size16_incast_disPoisson_packetFixed_dr1p67.json &
# python3 analytical_compare.py -c configFiles/config_size16_incast_disPoisson_packetFixed_dr3p33.json &
# python3 analytical_compare.py -c configFiles/config_size16_incast_disPoisson_packetFixed_dr5p0.json &
# python3 analytical_compare.py -c configFiles/config_size16_incast_disPoisson_packetUniform_dr1p67.json &
# python3 analytical_compare.py -c configFiles/config_size16_incast_disPoisson_packetUniform_dr3p33.json &
# python3 analytical_compare.py -c configFiles/config_size16_incast_disPoisson_packetUniform_dr5p0.json &
# python3 analytical_compare.py -c configFiles/config_size2000_alltoall_disGE_packetFixed_dr0p04.json &
# python3 analytical_compare.py -c configFiles/config_size2000_alltoall_disGE_packetUniform_dr0p04.json &
# python3 analytical_compare.py -c configFiles/config_size2000_alltoall_disPoisson_packetFixed_dr0p04.json &
# python3 analytical_compare.py -c configFiles/config_size2000_alltoall_disPoisson_packetUniform_dr0p04.json &
# python3 analytical_compare.py -c configFiles/config_size2000_broadcast_disGE_packetFixed_dr0p01.json &
# python3 analytical_compare.py -c configFiles/config_size2000_broadcast_disGE_packetFixed_dr0p03.json &
# python3 analytical_compare.py -c configFiles/config_size2000_broadcast_disGE_packetFixed_dr0p04.json &
# python3 analytical_compare.py -c configFiles/config_size2000_broadcast_disGE_packetUniform_dr0p01.json &
# python3 analytical_compare.py -c configFiles/config_size2000_broadcast_disGE_packetUniform_dr0p03.json &
# python3 analytical_compare.py -c configFiles/config_size2000_broadcast_disGE_packetUniform_dr0p04.json &
# python3 analytical_compare.py -c configFiles/config_size2000_broadcast_disPoisson_packetFixed_dr0p01.json &
# python3 analytical_compare.py -c configFiles/config_size2000_broadcast_disPoisson_packetFixed_dr0p03.json &
# python3 analytical_compare.py -c configFiles/config_size2000_broadcast_disPoisson_packetFixed_dr0p04.json &
# python3 analytical_compare.py -c configFiles/config_size2000_broadcast_disPoisson_packetUniform_dr0p01.json &
# python3 analytical_compare.py -c configFiles/config_size2000_broadcast_disPoisson_packetUniform_dr0p03.json &
# python3 analytical_compare.py -c configFiles/config_size2000_broadcast_disPoisson_packetUniform_dr0p04.json &
# python3 analytical_compare.py -c configFiles/config_size2000_incast_disGE_packetFixed_dr0p01.json &
# python3 analytical_compare.py -c configFiles/config_size2000_incast_disGE_packetFixed_dr0p03.json &
# python3 analytical_compare.py -c configFiles/config_size2000_incast_disGE_packetFixed_dr0p04.json &
# python3 analytical_compare.py -c configFiles/config_size2000_incast_disGE_packetUniform_dr0p01.json &
# python3 analytical_compare.py -c configFiles/config_size2000_incast_disGE_packetUniform_dr0p03.json &
# python3 analytical_compare.py -c configFiles/config_size2000_incast_disGE_packetUniform_dr0p04.json &
# python3 analytical_compare.py -c configFiles/config_size2000_incast_disPoisson_packetFixed_dr0p01.json &
# python3 analytical_compare.py -c configFiles/config_size2000_incast_disPoisson_packetFixed_dr0p03.json &
# python3 analytical_compare.py -c configFiles/config_size2000_incast_disPoisson_packetFixed_dr0p04.json &
# python3 analytical_compare.py -c configFiles/config_size2000_incast_disPoisson_packetUniform_dr0p01.json &
# python3 analytical_compare.py -c configFiles/config_size2000_incast_disPoisson_packetUniform_dr0p03.json &
# python3 analytical_compare.py -c configFiles/config_size2000_incast_disPoisson_packetUniform_dr0p04.json &
# python3 analytical_compare.py -c configFiles/config_size432_alltoall_disGE_packetFixed_dr0p06.json &
# python3 analytical_compare.py -c configFiles/config_size432_alltoall_disGE_packetFixed_dr0p12.json &
# python3 analytical_compare.py -c configFiles/config_size432_alltoall_disGE_packetFixed_dr0p17.json &
# python3 analytical_compare.py -c configFiles/config_size432_alltoall_disGE_packetUniform_dr0p06.json &
# python3 analytical_compare.py -c configFiles/config_size432_alltoall_disGE_packetUniform_dr0p12.json &
# python3 analytical_compare.py -c configFiles/config_size432_alltoall_disGE_packetUniform_dr0p17.json &
# python3 analytical_compare.py -c configFiles/config_size432_alltoall_disPoisson_packetFixed_dr0p06.json &
# python3 analytical_compare.py -c configFiles/config_size432_alltoall_disPoisson_packetFixed_dr0p12.json &
# python3 analytical_compare.py -c configFiles/config_size432_alltoall_disPoisson_packetFixed_dr0p17.json &
# python3 analytical_compare.py -c configFiles/config_size432_alltoall_disPoisson_packetUniform_dr0p06.json &
# python3 analytical_compare.py -c configFiles/config_size432_alltoall_disPoisson_packetUniform_dr0p12.json &
# python3 analytical_compare.py -c configFiles/config_size432_alltoall_disPoisson_packetUniform_dr0p17.json &
python3 analytical_compare.py -c configFiles/config_size432_broadcast_disGE_packetFixed_dr0p06.json &
python3 analytical_compare.py -c configFiles/config_size432_broadcast_disGE_packetFixed_dr0p12.json &
python3 analytical_compare.py -c configFiles/config_size432_broadcast_disGE_packetFixed_dr0p17.json &
python3 analytical_compare.py -c configFiles/config_size432_broadcast_disGE_packetUniform_dr0p06.json &
python3 analytical_compare.py -c configFiles/config_size432_broadcast_disGE_packetUniform_dr0p12.json &
python3 analytical_compare.py -c configFiles/config_size432_broadcast_disGE_packetUniform_dr0p17.json &
python3 analytical_compare.py -c configFiles/config_size432_broadcast_disPoisson_packetFixed_dr0p06.json &
python3 analytical_compare.py -c configFiles/config_size432_broadcast_disPoisson_packetFixed_dr0p12.json &
python3 analytical_compare.py -c configFiles/config_size432_broadcast_disPoisson_packetFixed_dr0p17.json &
python3 analytical_compare.py -c configFiles/config_size432_broadcast_disPoisson_packetUniform_dr0p06.json &
python3 analytical_compare.py -c configFiles/config_size432_broadcast_disPoisson_packetUniform_dr0p12.json &
python3 analytical_compare.py -c configFiles/config_size432_broadcast_disPoisson_packetUniform_dr0p17.json &
# python3 analytical_compare.py -c configFiles/config_size432_incast_disGE_packetFixed_dr0p06.json &
# python3 analytical_compare.py -c configFiles/config_size432_incast_disGE_packetFixed_dr0p12.json &
# python3 analytical_compare.py -c configFiles/config_size432_incast_disGE_packetFixed_dr0p17.json &
# python3 analytical_compare.py -c configFiles/config_size432_incast_disGE_packetUniform_dr0p06.json &
# python3 analytical_compare.py -c configFiles/config_size432_incast_disGE_packetUniform_dr0p12.json &
# python3 analytical_compare.py -c configFiles/config_size432_incast_disGE_packetUniform_dr0p17.json &
# python3 analytical_compare.py -c configFiles/config_size432_incast_disPoisson_packetFixed_dr0p06.json &
# python3 analytical_compare.py -c configFiles/config_size432_incast_disPoisson_packetFixed_dr0p12.json &
# python3 analytical_compare.py -c configFiles/config_size432_incast_disPoisson_packetFixed_dr0p17.json &
# python3 analytical_compare.py -c configFiles/config_size432_incast_disPoisson_packetUniform_dr0p06.json &
# python3 analytical_compare.py -c configFiles/config_size432_incast_disPoisson_packetUniform_dr0p12.json &
# python3 analytical_compare.py -c configFiles/config_size432_incast_disPoisson_packetUniform_dr0p17.json &
wait