## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_module('queue-monitor', ['internet', 'config-store', 'stats'])
    obj.source = ["model/%s" % s for s in [
       'queue-monitor.cc',
       'queue-probe.cc',
       'queue-log-v3.cc'
        ]]
    obj.source.append("helper/queue-monitor-helper.cc")

    module_test = bld.create_ns3_module_test_library('queue-monitor')
    module_test.source = [ ]

    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #   'test/flow-monitor-examples-test-suite.cc',
            ])
    
    headers = bld(features='ns3header')
    headers.module = 'queue-monitor'
    headers.source = ["model/%s" % s for s in [
       'queue-monitor.h',
       'queue-probe.h',
       'queue-log-v3.h'
        ]]
    headers.source.append("helper/queue-monitor-helper.h")

    if bld.env['ENABLE_EXAMPLES']:
        bld.recurse('examples')

    bld.ns3_python_bindings()
